name: Fail After Sleep

on:
  push:
    branches:
      - main  # Change this if needed
  pull_request:
    branches:
      - main  # Runs on PRs targeting `main`

jobs:
  sleep-and-fail:
    runs-on: ubuntu-latest

    steps:
      - name: Start Workflow
        run: echo "Starting workflow..."

      - name: Sleep for 30 seconds
        run: sleep 30

      - name: Fail intentionally
        run: exit 1


